{ lib, pkgs, inputs, config, ... }:
{
  xdg.dataFile = lib.mkIf config.desktop.enable {
    "wallpapers".source = inputs.gruvbox-wallpapers;
  };
  services.hyprpaper = {
    settings = {
      # ipc = "off";
      preload = [ "~/.cache/wall.png" ];
      wallpaper = [
        "eDP-1,~/.cache/wall.png"
      ];
    };
  };
  wayland.windowManager.hyprland.settings.exec-once = lib.mkIf config.services.hyprpaper.enable [ "swapwallpaper" ];
  home = lib.mkIf config.services.hyprpaper.enable {
    packages = [
      (pkgs.writeShellScriptBin "swapwallpaper" /*sh*/ ''
        paper="$HOME/.local/share/wallpapers/wallpapers/$(shuf -n 1 ~/.config/goodwps)"
        rm ~/.cache/wall.png
        ln -s "$paper" ~/.cache/wall.png
        hyprctl monitors -j | jq -r '.[].name' | xargs -I '{}' hyprctl hyprpaper reload "{},$paper"
      '')
    ];
    file.".config/goodwps".text = ''
      ./anime/5m5kLI9.png
      ./anime/Kita.png
      ./anime/Mandalorian.jpg
      ./anime/after_school_stroll_gruvbox.png
      ./anime/classroom.jpg
      ./anime/elias.jpg
      ./anime/gankutsuou.jpg
      ./anime/grey_lain_wallpaper.jpg
      ./anime/kurotani.jpg
      ./anime/sushi.jpg
      ./brands/firefox.png
      ./brands/gnu.jpg
      ./brands/gruvbox-nix.png
      ./brands/gruvbox-rainbow-nix.png
      ./brands/gruvbox_kubuntuGear.jpg
      ./brands/nix.png
      ./brands/nixos.png
      ./brands/nvim.png
      ./brands/sve.png
      ./brands/tux.png
      ./minimalistic/ALLqk82.png
      ./minimalistic/Boxes.png
      ./minimalistic/PJbX0MG.png
      ./minimalistic/atoms.png
      ./minimalistic/bunny.png
      ./minimalistic/burning-earth.png
      ./minimalistic/burnout.png
      ./minimalistic/chaos.png
      ./minimalistic/coding-2.png
      ./minimalistic/coding-3.png
      ./minimalistic/coding.png
      ./minimalistic/dark-bench.png
      ./minimalistic/door.png
      ./minimalistic/dragon.png
      ./minimalistic/elegant.png
      ./minimalistic/finalizer.png
      ./minimalistic/fingerprint.png
      ./minimalistic/fox.png
      ./minimalistic/freebsd.png
      ./minimalistic/gamepad.png
      ./minimalistic/girl-outline.png
      ./minimalistic/gnulinux.png
      ./minimalistic/great-wave-of-kanagawa-gruvbox.png
      ./minimalistic/gruv-abstract-maze.png
      ./minimalistic/gruv-commit.png
      ./minimalistic/gruv-dev-minimal.png
      ./minimalistic/gruv-estimate.png
      ./minimalistic/gruv-focus.png
      ./minimalistic/gruv-kanji.png
      ./minimalistic/gruv-limits.png
      ./minimalistic/gruv-mistakes.png
      ./minimalistic/gruv-portal-cake.png
      ./minimalistic/gruv-samurai-cyberpunk2077.png
      ./minimalistic/gruv-understand.png
      ./minimalistic/gruv.jpg
      ./minimalistic/gruvb_solarsys.png
      ./minimalistic/gruvbox-linux.png
      ./minimalistic/gruvbox_astro.jpg
      ./minimalistic/gruvbox_grid.png
      ./minimalistic/gruvbox_minimal_space.png
      ./minimalistic/gruvbox_spac.jpg
      ./minimalistic/gruvbox_tux.png
      ./minimalistic/haz-mat.png
      ./minimalistic/husky.png
      ./minimalistic/iuh3jkasndjans.jpg
      ./minimalistic/kiddae.jpg
      ./minimalistic/moon.png
      ./minimalistic/nasa-2.png
      ./minimalistic/nasa-3.png
      ./minimalistic/nasa.png
      ./minimalistic/orbit.png
      ./minimalistic/pacman-ghosts.png
      ./minimalistic/persepolis-shirdal.png
      ./minimalistic/philosophy.png
      ./minimalistic/ratm.png
      ./minimalistic/rocket.png
      ./minimalistic/rubiks-cube.png
      ./minimalistic/skull-2.png
      ./minimalistic/skull-3.png
      ./minimalistic/skull.png
      ./minimalistic/smile-2.png
      ./minimalistic/smile.png
      ./minimalistic/snake.png
      ./minimalistic/trisquel-gnu-linux.png
      ./minimalistic/uchiha-clan-logo.png
      ./minimalistic/vim.png
      ./minimalistic/wallpaper.png
      ./minimalistic/war-in-space.png
      ./minimalistic/wp11058333.png
      ./minimalistic/xxxtentacion.png
      ./mix/1.jpg
      ./mix/abstract-2.jpg
      ./mix/abstract-3.jpg
      ./mix/abstract-4.png
      ./mix/abstract-darkhole.png
      ./mix/abstract.jpg
      ./mix/alien_landscape.png
      ./mix/among-us.jpg
      ./mix/animal-skull.jpg
      ./mix/artificial-brain.jpg
      ./mix/astronaut.jpg
      ./mix/black-hole.png
      ./mix/chinatown.png
      ./mix/dalek.jpg
      ./mix/dead-robot.jpg
      ./mix/desk-gruvbox-material.jpg
      ./mix/evil.jpeg
      ./mix/flower.jpg
      ./mix/forest_castle.png
      ./mix/free.jpg
      ./mix/fsociety.jpg
      ./mix/future-town.jpg
      ./mix/futurism.jpg
      ./mix/galaxy.png
      ./mix/greek.png
      ./mix/gruv-material.png
      ./mix/gruv-sushi-streets.jpg
      ./mix/gruvb99810.png
      ./mix/gruvbox15.png
      ./mix/gruvy-night.jpg
      ./mix/gruvy.jpg
      ./mix/hotline-miami.jpg
      ./mix/houses.png
      ./mix/mad.jpg
      ./mix/mountain.jpg
      ./mix/night_moon.png
      ./mix/platform.jpg
      ./mix/qcqKfdZ.png
      ./mix/ruines.jpg
      ./mix/ruins-2.png
      ./mix/satellite.jpg
      ./mix/skull.jpg
      ./mix/solar-system.jpg
      ./mix/spaceship_maze.jpg
      ./mix/titlwinzbst81.jpg
      ./mix/wall.jpg
      ./mix/wallhaven-vmk698.jpg
      ./mix/warm_forest.png
      ./mix/xavier-cuenca-w4-3.jpg
      ./painting/A_Herefordshire_Lane.png
      ./painting/Cat_at_Play.png
      ./painting/Driving_Home_The_Flock.png
      ./painting/View_of_Vent_in_the_Ventertal.jpg
      ./photography/Colors.png
      ./photography/Pages.png
      ./photography/White-Mountain.jpg
      ./photography/YRAJQAT4Dg-avesta-rezaeizadeh-unsplash.jpg
      ./photography/aaron-burden-X3Um-nwpuWs.jpg
      ./photography/aj-robbie-BuQ1RZckYW4.jpg
      ./photography/ameenfahmy-mXpTl4jNKiA.jpg
      ./photography/beer.jpg
      ./photography/berries.jpg
      ./photography/board.png
      ./photography/books.jpg
      ./photography/bridge.jpg
      ./photography/bulbs.jpg
      ./photography/bush.png
      ./photography/cabin.png
      ./photography/cinnamon-rolls.jpg
      ./photography/clay-banks-Jya99orvzSE.jpg
      ./photography/coffee-cup.jpg
      ./photography/coffee-green.jpg
      ./photography/comfy-room.jpg
      ./photography/davide-ragusa-4jcFu1byopQ.jpg
      ./photography/edewaa-foster-aWkpMIIC5aY.jpg
      ./photography/explore-with-joshua-oI6EJabIYYQ.jpg
      ./photography/ferns-green.jpg
      ./photography/flower-1.jpg
      ./photography/flowers-2.jpg
      ./photography/flowers.jpg
      ./photography/fly_agaric_mushroom_fall_foliage_117318_1920x1080.jpg
      ./photography/forest-2.jpg
      ./photography/forest-3.jpg
      ./photography/forest-4.jpg
      ./photography/forest-5.jpg
      ./photography/forest-6.jpg
      ./photography/forest-7.jpg
      ./photography/forest-cabin.jpg
      ./photography/hannu-keski-hakuni-vgxIfXwsUAE.jpg
      ./photography/herb-notebook.png
      ./photography/jake-weirick-EsvpmQ4zp5Y.jpg
      ./photography/jakub-sejkora-utqJcneoFjo.jpg
      ./photography/jars.jpg
      ./photography/jeremy-hynes-_RnbxS6vUb8.jpg
      ./photography/johannes-plenio-RwHv7LgeC7s.jpg
      ./photography/joshua-sortino-Rnqa6jOpnHw.jpg
      ./photography/jr-korpa-YXQew2KZjzY.jpg
      ./photography/julentto-photography-Yr1SCCRJXIY.jpg
      ./photography/kateryna-sheliuk-6gI-RJ_WsHk.jpg
      ./photography/kateryna-sheliuk-dGFVlulYvK0.jpg
      ./photography/kateryna-sheliuk-efMADvDQvEg.jpg
      ./photography/keyboard.jpg
      ./photography/kristian-seedorff-BvUicqkaZZ0.jpg
      ./photography/lantern.jpg
      ./photography/leaves-2.jpg
      ./photography/leaves-3.jpg
      ./photography/leaves-4.jpg
      ./photography/leaves-hard.jpg
      ./photography/leaves-hard.jpg
      ./photography/leaves-wall.png
      ./photography/leaves.jpg
      ./photography/lukasz-szmigiel-ps2daRcXYes.jpg
      ./photography/maciek-sulkowski-eoXoU1wpvqs.jpg
      ./photography/marketplace.png
      ./photography/more-coffee.jpg
      ./photography/moss-forest.png
      ./photography/moss.jpg
      ./photography/mountain-village.png
      ./photography/mountains-2.png
      ./photography/mushroom.jpg
      ./photography/mushrooms-1.jpg
      ./photography/mushrooms.jpg
      ./photography/panel.jpg
      ./photography/plate-dark.jpg
      ./photography/rails-2.jpg
      ./photography/rails.jpg
      ./photography/rose01.png
      ./photography/saso-tusar-s-k-2N90yuY.jpg
      ./photography/sunforest.jpg
      ./photography/tangerines.jpg
      ./photography/teapots.jpg
      ./photography/timbers.jpg
      ./photography/tools.jpg
      ./photography/typewriter.jpg
      ./photography/village.jpg
      ./photography/wood.jpg
      ./pixelart/gruvbox_image46.png
      ./pixelart/gruvbox_image55.png
      ./pixelart/house-garden.png
      ./pixelart/image16.png
      ./pixelart/image21.png
      ./pixelart/wall_secondary.png
      ./renders/3d_gruvbox.png
      ./renders/orthvrq3xgb91.jpg
    '';
  };
}
