{ lib, config, pkgs, ... }:
let
  cfg = config.graphide.checkoutSync;

  # The shared main checkout. Not a worktree, ever: nothing is authored in the
  # main checkout (a hook blocks `git commit` on master there and all work
  # happens on a branch in ../graphide-<name>), which is the whole reason the
  # allowlist below can discard a local diff without asking. Point this at a
  # worktree and that reasoning inverts -- a dirty file there is real work.
  defaultCheckout = "/home/greencheetah/Projects/graphide/graphide";

  # Two tracked paths that two local processes rewrite continuously, and the
  # only reason the checkout sat 30 commits behind origin/master on 2026-09-11
  # while being 0 ahead. Neither is gitignorable, and both were checked:
  #
  #   .graphide/authored/**  -- monolith .gitignore:91-93 ignores `.graphide/*`
  #     then un-ignores `!.graphide/authored/`, commented "the authored graph
  #     travels in git; everything else under .graphide/ is local". The grug
  #     daemon rewrites these shards from the local graph.db on every sync, so
  #     the working copy drifts from HEAD by design. Regenerated by `gr sync`.
  #
  #   gred/extensions/graphide/out/**  -- gred/CLAUDE.md:58, "the built
  #     artifacts in extensions/graphide/out/ should be committed alongside
  #     their source changes", and flake.nix:196/:4112 read the TRACKED copy
  #     (gredExtOutPaths, trackedOut=) as a build input. Gitignoring it would
  #     break the flake's gred build. Regenerated by the extension compile.
  #
  # Anything dirty outside this list aborts the run untouched.
  defaultAllowlist = [
    ".graphide/authored"
    "gred/extensions/graphide/out"
  ];

  syncScript = pkgs.writeShellApplication {
    name = "graphide-checkout-sync";
    runtimeInputs = [
      pkgs.git
      pkgs.openssh
      pkgs.util-linux
      pkgs.libnotify
      pkgs.coreutils
    ];
    text = ''
      CHECKOUT=${lib.escapeShellArg cfg.checkout}
      BRANCH=${lib.escapeShellArg cfg.branch}
      REMOTE=${lib.escapeShellArg cfg.remote}
      ALLOWLIST=(${lib.concatMapStringsSep " " lib.escapeShellArg cfg.allowlist})

      note() { echo "graphide-checkout-sync: $1"; }

      # Escalation channel. The script handles the case it was built for and
      # NOTHING else; every refusal below is a human's call, so it has to be
      # visible rather than buried in `journalctl --user`.
      escalate() {
        note "$1"
        notify-send -u normal "Graphide checkout out of sync" "$1" || true
      }

      # Guards two runs of this unit against each other only. A peer session
      # running git in the same checkout is caught by .git/index.lock below,
      # and by git's own locking.
      exec 9>"''${XDG_RUNTIME_DIR:-/tmp}/graphide-checkout-sync.lock"
      if ! flock -n 9; then
        note "another run holds the lock, skipping"
        exit 0
      fi

      cd "$CHECKOUT" || { note "checkout $CHECKOUT is missing"; exit 0; }

      gitdir=$(git rev-parse --git-dir 2>/dev/null) || {
        note "$CHECKOUT is not a git checkout"; exit 0; }

      # Never touch a checkout that is not sitting on the branch we sync, and
      # never one that is mid-operation. A leftover .git/AUTO_MERGE from an
      # aborted merge is not itself blocking, so it is deliberately not here.
      head=$(git symbolic-ref --quiet --short HEAD 2>/dev/null || echo "(detached)")
      if [ "$head" != "$BRANCH" ]; then
        note "HEAD is $head, not $BRANCH, leaving it alone"
        exit 0
      fi
      for marker in MERGE_HEAD REVERT_HEAD CHERRY_PICK_HEAD BISECT_LOG \
                    rebase-merge rebase-apply index.lock; do
        if [ -e "$gitdir/$marker" ]; then
          note "$marker present, a git operation is in flight, skipping"
          exit 0
        fi
      done

      # Soft-fail on the network. The timer comes back; a red unit every cycle
      # on a train is noise, not information.
      if ! git fetch --quiet --prune "$REMOTE" "$BRANCH" 2>/dev/null; then
        note "fetch failed, will retry next cycle"
        exit 0
      fi

      # An index that has not been refreshed reports files as modified purely
      # because their mtime moved, which in a checkout this busy inflates the
      # dirty list enough to make every run refuse.
      git update-index --refresh -q >/dev/null 2>&1 || true

      behind=$(git rev-list --count "HEAD..$REMOTE/$BRANCH")
      ahead=$(git rev-list --count "$REMOTE/$BRANCH..HEAD")

      if [ "$behind" -eq 0 ]; then
        note "already up to date with $REMOTE/$BRANCH"
        exit 0
      fi

      # Cannot happen while the commit hook holds: nothing is committed on
      # master in the main checkout. If it ever does, it is a commit that
      # exists in exactly one place on earth, so this script must not go near
      # it -- no merge, no rebase, no reset.
      if [ "$ahead" -ne 0 ]; then
        escalate "$BRANCH is $ahead ahead and $behind behind $REMOTE/$BRANCH. Local commits in the main checkout are unexpected; resolve by hand."
        exit 0
      fi

      # Every dirty path must fall inside the allowlist. Renames and copies are
      # refused outright: they are not something either generator produces, so
      # one here means a human moved something.
      blockers=()
      while IFS= read -r -d ''' rec; do
        [ -n "$rec" ] || continue
        status=''${rec:0:2}
        path=''${rec:3}
        case "$status" in
          R*|C*) blockers+=("$path (rename/copy)"); continue ;;
        esac
        allowed=0
        for a in "''${ALLOWLIST[@]}"; do
          case "$path" in
            "$a"|"$a"/*) allowed=1; break ;;
          esac
        done
        [ "$allowed" -eq 1 ] || blockers+=("$path")
      done < <(git status --porcelain=v1 -z --untracked-files=all)

      if [ ''${#blockers[@]} -gt 0 ]; then
        escalate "$behind behind $REMOTE/$BRANCH, blocked by ''${#blockers[@]} dirty path(s) outside the generated allowlist, first: ''${blockers[0]}"
        exit 0
      fi

      # Only generated, regenerable paths are dirty. Drop them and fast-forward.
      #
      # --ff-only and nothing else. A real merge would create a commit on
      # master in a checkout where committing on master is a hook violation; a
      # rebase would rewrite shared history; `git stash` is barred outright
      # here because the stash stack is repo-global and concurrent pops swap
      # stashes between sessions.
      if [ ''${#ALLOWLIST[@]} -gt 0 ]; then
        git restore --source=HEAD --staged --worktree -- "''${ALLOWLIST[@]}" \
          >/dev/null 2>&1 || true
        # Untracked-only, never -x: the ignored siblings under .graphide/ are
        # graph.db and the local scaffold, which this must not delete. Clears
        # the external%3A*.jsonl left by the colon shard rename, which collide
        # by name with files the incoming commits add.
        git clean -fdq -- "''${ALLOWLIST[@]}" >/dev/null 2>&1 || true
      fi

      if git merge --ff-only "$REMOTE/$BRANCH" >/dev/null 2>&1; then
        note "fast-forwarded $BRANCH by $behind commit(s) to $(git rev-parse --short HEAD)"
        exit 0
      fi

      escalate "fast-forward of $BRANCH failed after clearing the generated paths ($behind behind). Needs a look."
      exit 0
    '';
  };
in
{
  options.graphide.checkoutSync = {
    enable = lib.mkEnableOption ''
      a user timer that fast-forwards the shared main graphide checkout to
      origin/master, discarding only the two generated paths that otherwise
      block it. It never merges, never rebases, never stashes, and never
      touches a checkout that is ahead or dirty outside that allowlist
    '';

    checkout = lib.mkOption {
      type = lib.types.str;
      default = defaultCheckout;
      description = "Main checkout to keep fast-forwarded. Must not be a worktree.";
    };

    branch = lib.mkOption {
      type = lib.types.str;
      default = "master";
      description = "Branch to sync. The run is a no-op unless HEAD is on it.";
    };

    remote = lib.mkOption {
      type = lib.types.str;
      default = "origin";
      description = "Remote to fast-forward from.";
    };

    allowlist = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = defaultAllowlist;
      description = ''
        Repo-relative prefixes whose local state may be discarded to unblock
        the fast-forward. Every entry must be regenerable from something else
        on this machine; see the comment above defaultAllowlist for why these
        two are tracked rather than gitignored.
      '';
    };

    interval = lib.mkOption {
      type = lib.types.str;
      default = "30m";
      description = "OnUnitActiveSec for the sync timer.";
    };
  };

  config = lib.mkIf (config.graphide.enable && cfg.enable) {
    systemd.user.services.graphide-checkout-sync = {
      Unit = {
        Description = "Fast-forward the shared graphide main checkout to origin/master";
        After = [ "network-online.target" ];
        Wants = [ "network-online.target" ];
      };
      Service = {
        Type = "oneshot";
        ExecStart = lib.getExe syncScript;
        # The same agent-held SSH key the shell uses; the repo is private and
        # this machine has no GitHub token in nix.conf.
        Environment = [ "SSH_AUTH_SOCK=%t/ssh-agent" ];
        # Must never win a scheduling fight with the editor or a test run.
        Nice = 10;
        IOSchedulingClass = "idle";
      };
    };

    systemd.user.timers.graphide-checkout-sync = {
      Unit.Description = "Check whether the graphide main checkout is behind origin/master";
      Timer = {
        # Offset from graphide-autoupdate's 5m so the two do not contend for
        # the network, the ssh agent, or the disk on every login.
        OnStartupSec = "8m";
        OnUnitActiveSec = cfg.interval;
        RandomizedDelaySec = "2m";
        Persistent = true;
      };
      Install.WantedBy = [ "timers.target" ];
    };
  };
}
