{ config, lib, pkgs, ... }:

let
  cfg = config.serv.youHaveMail;

  user = "you-have-mail";
  stateDir = "/var/lib/you-have-mail";
  logDir = "${stateDir}/logs";
  configFile = "${stateDir}/config.toml";

  # Auth tokens are read from out-of-store files at start-up and substituted
  # into the rendered config, so they never land in the world-readable store.
  tokenPlaceholder = i: "@NTFY_AUTH_TOKEN_${toString i}@";

  accountBlock = account: ''

    [[account]]
    email = ${builtins.toJSON account.email}
    backend = ${builtins.toJSON account.backend}
  '';

  ntfyBlock = i: server: ''

    [[ntfy]]
    name = ${builtins.toJSON server.name}
    url = ${builtins.toJSON server.url}
  '' + lib.optionalString (server.authTokenFile != null) ''
    auth_token = "${tokenPlaceholder i}"
  '';

  configTemplate = pkgs.writeText "you-have-mail-config.toml" (''
    # Generated by the serv.youHaveMail module; overwritten on every start.
    # "Plain" keeps the state-encryption key in a 0600 file beside this one.
    # The alternative, "Keyring", needs a login session this service never has,
    # and its kernel-keyring backend would not survive a reboot.
    secrets = "Plain"
    accept_plain_secrets_insecure = true
    poll_interval = ${toString cfg.pollInterval}
    stdout_notifier = ${lib.boolToString cfg.stdoutNotifier}
  ''
    + lib.concatStrings (map accountBlock cfg.accounts)
    + lib.concatStrings (lib.imap0 ntfyBlock cfg.ntfy));

  installConfig = pkgs.writeShellScript "you-have-mail-install-config" ''
    set -euo pipefail

    install -d -m 0700 -o ${user} -g ${user} ${stateDir} ${logDir}

    umask 077
    tmp="$(mktemp)"
    trap 'rm -f "$tmp"' EXIT
    cp ${configTemplate} "$tmp"

    ${lib.concatStrings (lib.imap0 (i: server:
      lib.optionalString (server.authTokenFile != null) ''
        token="$(cat ${lib.escapeShellArg server.authTokenFile})"
        sed -i "s|${tokenPlaceholder i}|$token|g" "$tmp"
      '') cfg.ntfy)}

    install -m 0600 -o ${user} -g ${user} "$tmp" ${configFile}
  '';

  # Accounts can only be added through an interactive password/TOTP prompt, so
  # this wraps the one-time login: stop the observer (it holds the same state
  # file), refresh the config, prompt, then bring the observer back up.
  setupScript = pkgs.writeShellScriptBin "you-have-mail-setup" ''
    set -euo pipefail

    if [ "$(id -u)" -ne 0 ]; then
      echo "you-have-mail-setup must be run as root" >&2
      exit 1
    fi

    systemctl stop you-have-mail.service || true
    systemctl restart you-have-mail-config.service

    runuser -u ${user} -- ${cfg.package}/bin/you-have-mail-cli \
      --config-dir ${stateDir} --log-dir ${logDir} --configure-accounts

    systemctl start you-have-mail.service
    echo "Observer restarted. Follow it with: journalctl -fu you-have-mail"
  '';
in
{
  options.serv.youHaveMail = {
    enable = lib.mkEnableOption "You Have Mail email notification observer";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.you-have-mail-cli;
      defaultText = lib.literalExpression "pkgs.you-have-mail-cli";
      description = "The you-have-mail-cli package to use.";
    };

    pollInterval = lib.mkOption {
      type = lib.types.ints.positive;
      default = 300;
      description = ''
        Seconds between mailbox polls. Proton throttles aggressive clients, so
        keep this comfortably above a minute.
      '';
    };

    stdoutNotifier = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Echo every notification to the journal as well as to ntfy.";
    };

    accounts = lib.mkOption {
      default = [ ];
      description = ''
        Accounts to watch. Listing an account here does not log it in — run
        `you-have-mail-setup` once afterwards to supply the password and TOTP.
      '';
      type = lib.types.listOf (lib.types.submodule {
        options = {
          email = lib.mkOption {
            type = lib.types.str;
            description = "Address of the account to watch.";
          };
          backend = lib.mkOption {
            type = lib.types.str;
            default = "Proton Mail";
            description = "Backend name, as registered by you-have-mail-common.";
          };
        };
      });
    };

    ntfy = lib.mkOption {
      default = [ ];
      description = "ntfy instances to publish notifications to.";
      type = lib.types.listOf (lib.types.submodule {
        options = {
          name = lib.mkOption {
            type = lib.types.str;
            description = "Label for this instance, used in the service logs.";
          };
          url = lib.mkOption {
            type = lib.types.str;
            example = "https://ntfy.sh/some-unguessable-topic";
            description = ''
              Full topic URL to POST to. This ends up in the Nix store, which is
              world-readable, and anyone who knows a topic can read and write it
              — so treat the topic name as public and rely on authTokenFile for
              access control on instances that support it.
            '';
          };
          authTokenFile = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            example = "/var/lib/secrets/ntfy-token";
            description = ''
              Absolute path, on the target machine, to a file holding the ntfy
              access token. Deliberately a string rather than a path so the
              secret is never copied into the Nix store.
            '';
          };
        };
      });
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.ntfy != [ ] || cfg.stdoutNotifier;
        message = ''
          serv.youHaveMail needs at least one notifier: add an entry to
          serv.youHaveMail.ntfy or set serv.youHaveMail.stdoutNotifier = true.
          The service refuses to start without one.
        '';
      }
    ];

    users.users.${user} = {
      isSystemUser = true;
      group = user;
      home = stateDir;
      description = "You Have Mail observer";
    };
    users.groups.${user} = { };

    environment.systemPackages = [ setupScript ];

    systemd.services.you-have-mail-config = {
      description = "Render the You Have Mail configuration file";
      wantedBy = [ "multi-user.target" ];
      before = [ "you-have-mail.service" ];
      requiredBy = [ "you-have-mail.service" ];
      path = with pkgs; [ coreutils gnused ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = installConfig;
      };
    };

    systemd.services.you-have-mail = {
      description = "You Have Mail email notification observer";
      wantedBy = [ "multi-user.target" ];
      wants = [ "network-online.target" ];
      after = [ "network-online.target" "you-have-mail-config.service" ];
      serviceConfig = {
        User = user;
        Group = user;
        ExecStart = "${cfg.package}/bin/you-have-mail-cli --config-dir ${stateDir} --log-dir ${logDir}";
        Restart = "always";
        RestartSec = 30;
        WorkingDirectory = stateDir;

        NoNewPrivileges = true;
        PrivateTmp = true;
        PrivateDevices = true;
        ProtectHome = true;
        ProtectSystem = "strict";
        ReadWritePaths = [ stateDir ];
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;
        RestrictNamespaces = true;
        RestrictRealtime = true;
        LockPersonality = true;
        SystemCallArchitectures = "native";
      };
    };
  };
}
